[resolver]
incompatible-rust-versions = "fallback"

[target.'cfg(all())']
# Note: if the RUSTFLAGS environment variable is set, this will be
# ignored.
rustflags = [
          "-Aunused-parens",
          "-Aunused-macros",
]
